/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduationproject;

import java.util.Random;

/**
 *
 * @author Milhim
 */
public class ColoringALgorithm extends javax.swing.JFrame {

    VertexCase v;
    GraphColoring g;
    Bipartite b;

    /**
     * Creates new form ColoringALgoeithm
     */
    public ColoringALgorithm() {
	  initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphSize = new javax.swing.JTextField();
        createGraph = new javax.swing.JButton();
        sideOne = new javax.swing.JTextField();
        sideTwo = new javax.swing.JTextField();
        addEdge = new javax.swing.JButton();
        numberOfVertex = new javax.swing.JTextField();
        numberOfEdges = new javax.swing.JTextField();
        createRandomGraph = new javax.swing.JButton();
        NumberOfColor1 = new javax.swing.JTextField();
        time1 = new javax.swing.JTextField();
        colorButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        colorButton3 = new javax.swing.JButton();
        NumberOfColor3 = new javax.swing.JTextField();
        time3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        colorButton4 = new javax.swing.JButton();
        NumberOfColor4 = new javax.swing.JTextField();
        time4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        graphSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphSizeActionPerformed(evt);
            }
        });

        createGraph.setBackground(new java.awt.Color(0, 204, 102));
        createGraph.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        createGraph.setForeground(new java.awt.Color(0, 51, 255));
        createGraph.setText("Generate non-random Graph ");
        createGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGraphActionPerformed(evt);
            }
        });

        sideOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideOneActionPerformed(evt);
            }
        });

        sideTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideTwoActionPerformed(evt);
            }
        });

        addEdge.setBackground(new java.awt.Color(0, 204, 102));
        addEdge.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addEdge.setForeground(new java.awt.Color(0, 51, 255));
        addEdge.setText("Add Edge");
        addEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeActionPerformed(evt);
            }
        });

        createRandomGraph.setBackground(new java.awt.Color(0, 204, 102));
        createRandomGraph.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        createRandomGraph.setForeground(new java.awt.Color(0, 51, 255));
        createRandomGraph.setText("Create Random Graph");
        createRandomGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRandomGraphActionPerformed(evt);
            }
        });

        NumberOfColor1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        time1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        colorButton1.setBackground(new java.awt.Color(255, 0, 51));
        colorButton1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        colorButton1.setForeground(new java.awt.Color(255, 255, 255));
        colorButton1.setText("Applay vertex Case algoritm");
        colorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("     Applying  Coloring Algorithm On a Random Graph");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Enter The Size OF Your Graph :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Enter The First Vertex Of Your Edge :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Enter The Second Vertex Of Your Edge : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Number Of Vertex : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Number Of Edges : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Number Of Color : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Elapsed time : ");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear All Field");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Number Of Color : ");

        colorButton3.setBackground(new java.awt.Color(255, 0, 51));
        colorButton3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        colorButton3.setForeground(new java.awt.Color(255, 255, 255));
        colorButton3.setText("Applay backtracking  algoritm");
        colorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton3ActionPerformed(evt);
            }
        });

        NumberOfColor3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        time3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Elapsed time : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("set m :");

        m.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        colorButton4.setBackground(new java.awt.Color(255, 0, 51));
        colorButton4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        colorButton4.setForeground(new java.awt.Color(255, 255, 255));
        colorButton4.setText("Applay Bipartite algoritm");
        colorButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton4ActionPerformed(evt);
            }
        });

        NumberOfColor4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        time4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Elapsed time : ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Number Of Color : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(sideTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfEdges, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(createRandomGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(graphSize, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(createGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(sideOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(colorButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel7)
                                            .addGap(16, 16, 16)
                                            .addComponent(NumberOfColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(104, 104, 104)
                                            .addComponent(colorButton1)))
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(114, 114, 114)
                                            .addComponent(colorButton4)
                                            .addGap(3, 3, 3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(16, 16, 16)
                                                .addComponent(NumberOfColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel14)
                                                .addGap(39, 39, 39)
                                                .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(128, 128, 128)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addComponent(jLabel12)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(510, 510, 510)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumberOfColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(graphSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(createGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sideOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(sideTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(numberOfEdges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createRandomGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(NumberOfColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(NumberOfColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(NumberOfColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graphSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphSizeActionPerformed
	  // TODO add your handling code here:
    }//GEN-LAST:event_graphSizeActionPerformed

    private void sideOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideOneActionPerformed
	  // TODO add your handling code here:
    }//GEN-LAST:event_sideOneActionPerformed

    private void createGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGraphActionPerformed
	  int size = Integer.parseInt(graphSize.getText());
	  v = new VertexCase(size);
	  g = new GraphColoring(size);
	  b = new Bipartite(size);
	  // TODO add your handling code here:
    }//GEN-LAST:event_createGraphActionPerformed

    private void addEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeActionPerformed

	  int x = Integer.parseInt(sideOne.getText());
	  int y = Integer.parseInt(sideTwo.getText());
	  v.addedge(x, y);
	  g.addedge(x, y);
	  sideOne.setText("");
	  sideTwo.setText("");

	  // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeActionPerformed

    private void createRandomGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRandomGraphActionPerformed
	  Random v1 = new Random();
	  int size = Integer.parseInt(numberOfVertex.getText());
	  v = new VertexCase(size);
	  g = new GraphColoring(size);
	  b = new Bipartite(size);
	  int edgesNumber = Integer.parseInt(numberOfEdges.getText());
	  int x;
	  int y;
	  while (edgesNumber > 0) {
		x = v1.nextInt(size);
		y = v1.nextInt(size);

		if (x != y && v.undirectedGraph[x][y]==false && b.undirectedGraph[x][y]==false && g.graph[x][y]==0) {
		    v.addedge(x, y);
		    g.addedge(x, y);
		    b.addedge(x, y);
		    System.out.println("edge "+x+" and "+y);
		    edgesNumber--;
		}
	  }
	  // TODO add your handling code here:
    }//GEN-LAST:event_createRandomGraphActionPerformed

    private void sideTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideTwoActionPerformed
	  // TODO add your handling code here:
    }//GEN-LAST:event_sideTwoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

	  graphSize.setText("");
	  numberOfEdges.setText("");
	  numberOfVertex.setText("");
	  NumberOfColor1.setText("");
	  time1.setText("");
	  sideOne.setText("");
	  sideTwo.setText("");

	  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton1ActionPerformed
	  long start = System.nanoTime();
	  int x = v.specialCase();
	  long end = System.nanoTime();
	  double totalTime = (double) (end - start) / 1000000000;
	  double modTime = (double) (end - start) % 1000000000;
	  if (x == -10) {
		NumberOfColor1.setText("not a special case try another alg");

	  } else {
		NumberOfColor1.setText(3 + " Color to Coloring The Graph");

	  }
	  time1.setText("Coloring toke : " + (int) totalTime + "." + (int) modTime + " sec. ");
	  // TODO add your handling code here:
    }//GEN-LAST:event_colorButton1ActionPerformed

    private void colorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton3ActionPerformed
	  long start = System.nanoTime();
	  int mcolor = Integer.parseInt(m.getText());
	  g.setm(mcolor);
	  g.mColoring(-1);
	  long end = System.nanoTime();
	  double totalTime = (double) (end - start) / 1000000000;
	  double modTime = (double) (end - start) % 1000000000;
	
	  NumberOfColor3.setText(mcolor + " Color to Coloring The Graph");
	  time3.setText("Coloring toke : " + (int) totalTime + "." + (int) modTime + " sec. ");
	  // TODO add your handling code here:
    }//GEN-LAST:event_colorButton3ActionPerformed

    private void colorButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton4ActionPerformed

	  long start = System.nanoTime();
	  if (b.isBipartite()) {
		NumberOfColor4.setText(2 + " Color to Coloring The Graph");
	  } else {
		NumberOfColor4.setText("not a bipartite  try another alg");

	  }
	  long end = System.nanoTime();
	  double totalTime = (double) (end - start) / 1000000000;
	  double modTime = (double) (end - start) % 1000000000;

	  time4.setText("Coloring toke : " + (int) totalTime + "." + (int) modTime + " sec. ");

	  // TODO add your handling code here:
    }//GEN-LAST:event_colorButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	  /* Set the Nimbus look and feel */
	  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	   */
	  try {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		    if ("Nimbus".equals(info.getName())) {
			  javax.swing.UIManager.setLookAndFeel(info.getClassName());
			  break;
		    }
		}
	  } catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(ColoringALgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(ColoringALgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(ColoringALgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(ColoringALgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  }
	  //</editor-fold>
	  //</editor-fold>
	  //</editor-fold>
	  //</editor-fold>

	  /* Create and display the form */
	  java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
		    new ColoringALgorithm().setVisible(true);
		}
	  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumberOfColor1;
    private javax.swing.JTextField NumberOfColor3;
    private javax.swing.JTextField NumberOfColor4;
    private javax.swing.JButton addEdge;
    private javax.swing.JButton colorButton1;
    private javax.swing.JButton colorButton3;
    private javax.swing.JButton colorButton4;
    private javax.swing.JButton createGraph;
    private javax.swing.JButton createRandomGraph;
    private javax.swing.JTextField graphSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField m;
    private javax.swing.JTextField numberOfEdges;
    private javax.swing.JTextField numberOfVertex;
    private javax.swing.JTextField sideOne;
    private javax.swing.JTextField sideTwo;
    private javax.swing.JTextField time1;
    private javax.swing.JTextField time3;
    private javax.swing.JTextField time4;
    // End of variables declaration//GEN-END:variables
}
